services:
  cpp-algos:
    build: ./cpp-algos
    ports:
      - "8080:8080"
    networks:
      - investor-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      # This passes the API key from your computer to the container.
      # Ensure you have a .env file in this folder or the backend folder.
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    depends_on:
      - cpp-algos
    networks:
      - investor-net

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - investor-net

networks:
  investor-net: